## Multistage Docker Build for Static Webpage Front-end (No Broswer Storage Functionality)

# Stage 1: Build the application
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build --optimize-images

# Stage 2: Create the production image
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/package.json .
COPY --from=builder /app/package-lock.json .
COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/.next/standalone .
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV production
EXPOSE 3000
ENTRYPOINT [ "node", "server.js" ]

# Run docker run -it --rm -dp 3000:3000 --name container-name image-name:version

# Note
# Add output: standalone in config
