# Can used by Vite too
FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:20-alpine AS prod

COPY --from=base /app/dist ./dist

COPY --from=base /app/index.js .

EXPOSE 3000

CMD ["node", "index.js"]
